---
title: "MT5763 Group Project"
author: "El Topo"
output:
  html_notebook:
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '2'
    highlight: tango
  word_document:
    toc: yes
    toc_depth: '2'
---

# Bootstrap Functions for SAS and R 

This section is to elucidate how the two functions work and to be implemented and illustrated with an analysis of a simple example with plots and interpretation.  The corresponding data set was uploaded in the repository. 

## SAS

The SAS Bootstrap Function generated the 95% Confidence Intervals for the mean, the mean estimate for each parameter and the corresponding plots of the distrubtion of the bootstrap parameters.

## R

```{r Bootstrap}



```
### Micro-Benchmark of our R bootstrap against package **boot** bootstraps


-----------------------

# Appendix

## Reference List

RStudio Team (2018). RStudio: Integrated Development for R. RStudio, Inc., Boston, MA URL <http://www.rstudio.com/>.

C. Donovan (2018). MT5763 Project 2 - code collaboration and computer intensive inference. Available at <https://moody.st-andrews.ac.uk/moodle/pluginfile.php/705037/mod_resource/content/1/MT5763_project%202%20description.nb.html> (Accessed at 29 Oct 2018) 